project:
  type: website

website:
  title: "Log([J]onathan [And]rew [P]edroza)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: jp_style.css
    toc: true

editor: visual

