project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - jp_style.css

website:
  title: "Log([J]onathan [And]rew [P]edroza)"
  navbar:
    left:
      - href: index.qmd
        text: Posts
      - about.qmd

format:
  html:
    theme: minty
    css: jp_style.css
    toc: true

editor: visual

