project:
  type: website

website:
  title: "Jonathan A. Pedroza"
  navbar:
    left:
      - href: resources.qmd
      #- href: index.qmd
      - href: posts.qmd

format:
  html:
    grid:
      #sidebar-width: 0px
      body-width: 1300px
      #margin-width: 0px
      gutter-width: 1.5rem
    theme: lumen
    # page-layout: full
    css: jp_style.css
    toc: true

editor: visual

