project:
  type: website

website:
  title: "Log([J]onathan [And]rew [P]edroza)"
  navbar:
    left:
      - href: index.qmd
        text: Posts
      - about.qmd

format:
  html:
    theme: minty
    page-layout: full
    css: jp_style.css
    toc: true

editor: visual

