project:
  type: website

website:
  title: "Jonathan A. Pedroza PhD"
  navbar:
    left:
      - href: posts.qmd
      - href: projects.qmd
      - href: resources.qmd
      - href: cv.qmd
    right:
      - icon: bluesky
        # text: BlueSky
        href: https://bsky.app/profile/jonathanpedroza.bsky.social
      - icon: mastodon
        # text: Mastodon
        href: https://fosstodon.org/@jpedroza
      - icon: linkedin
        # text: LinkedIn
        href: https://www.linkedin.com/in/jonathan-a-pedroza-phd-5721a7120/
      - icon: github
        # text: Github
        href: https://github.com/jpedroza1228
      - icon: mortarboard
        # text: Google Scholar
        href: https://scholar.google.com/citations?user=_LpAFsIAAAAJ&hl=en&oi=ao

format:
  html:
    grid:
      #sidebar-width: 0px
      body-width: 1300px
      #margin-width: 0px
      gutter-width: 1.5rem
    theme: lumen
    # page-layout: full
    css: jp_style.css
    toc: true

editor: visual