{
  "hash": "35208a532ca5e97c59231367593da31c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Twitter Conference Presentation\" \nsubtitle: |\n  Post about my presentation I gave over Twitter for the American Public Health Association's Physical Activity section.\nimage: la_dodgers.jpg\ncategories: [R, ggplot2, Hierarchical Linear Modeling, Multilevel Modeling, Modeling]\ndate: 2021-04-30\nexecute:\n  warning: false\n  message: false\nparams:\n  slug: Twitter-Conference-Presentation\n  date: 2021-04-30\n---\n\n![Photo by [Sean Pierce](https://unsplash.com/@prevailz?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash) on [Unsplash](https://unsplash.com/photos/an-aerial-view-of-a-baseball-stadium-with-a-city-in-the-background-jYHC1xSk-EE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash)](la_dodgers.jpg){fig-alt=\"An image of dodger stadium with Los Angles in the background.\" fig-align=\"left\" width=\"6in\" height=\"6in\"}\n\nI thought I'd talk about the analyses I conducted for my submission to the American Public Health Association Physical Activity Section's Twitter Conference. I thought it was a fun opportunity to disseminate some analyses that I conducted using public data from the [County Health Rankings and Roadmap](https://www.countyhealthrankings.org/) to examine what factors are associated with leisure-time physical activity (LTPA) in counties in California from 2016 to 2020. If you are interested in the presentation itself, you can follow it [here](https://twitter.com/PaSectionAPHA/status/1309192269447143425).\n\nPhysical activity is important as its related to many physical and mental health conditions. It is also a health behavior that can be modified slightly easier than other health behaviors. While not as beneficial as extended periods of exercise, even walking for leisure can be beneficial for one's health. I was predominately interested in California because I wanted to know how much variation there was between the counties. For instance, there are areas like San Francisco county and Los Angeles County, which may be seen as hubs for cultures of being physically active, but what about counties throughout Central California. I'm also interested in LTPA engagement because this health behavior has several social determinants of health that impact how much LTPA individuals can engage in. The social determinant that I'm most interested in is the role that access to recreational facilities and parks have on counties' LTPA engagement. Since I was interested in looking at variation between counties while also examining the longitudinal association between access and LTPA, I decided to create a two-level multilevel model with time (level 1) nested within counties (level 2).\n\n### Packages ued\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(inspectdf)\nlibrary(psych)\nlibrary(lme4)\nlibrary(lmerTest)\nlibrary(optimx)\n# library(ggmap)\nlibrary(maps)\nlibrary(RColorBrewer)\nlibrary(ggrepel)\nlibrary(gganimate)\nlibrary(transformr)\n\n# display.brewer.all()\n\noptions(max.print = 99999)\noptions(scipen = 999)\ntheme_set(theme_minimal())\n```\n:::\n\n\n### Functions\n\nBefore beginning I created a simple function to get the intraclass correlation coefficient (ICC). I also included a function to get data from the 5 years of County Health Rankings data. The function to get the ICC from random-intercept models is the between county variation divided by the total variation between counties and within counties. This gives you information about how much of the variation in the model can be attributed to differences between counties regarding your outcome. Random-intercept models were tested because I was only interested in knowing the variation in counties' LTPA engagement. There were also not enough points for each county to test individual slopes for each county (random-slopes model).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_icc_2level <- function(multi_model){\n  between <- multi_model$vcov[1]\n  total <- multi_model$vcov[1] + multi_model$vcov[2]\n  \n  between/total\n}\ncounties <- function(years){\n  \n  link <- glue::glue('https://raw.githubusercontent.com/jpedroza1228/dissertation/master/final_data/county{years}_sub.csv')\n  \n  rio::import(link, setclass = 'tibble')\n  \n}\nlibrary(curl)\n\ncounty <- map_df(16:20, ~counties(.x))\ncounty <- county |> \n  dplyr::select(rowid,\n                state_fips_code:release_year,\n                poor_or_fair_health:access_to_exercise_opportunities,\n                preventable_hospital_stays,\n                some_college:driving_alone_to_work,\n                food_insecurity:uninsured_children,\n                median_household_income:percent_rural) |> \n  mutate(year = release_year,\n         state = state_abbreviation,\n         phyact_percent = (physical_inactivity*100),\n         ltpa_percent = (100 - phyact_percent),\n         smoking_percent = adult_smoking*100,\n         obesity_percent = adult_obesity*100,\n         access_pa_percent = access_to_exercise_opportunities*100,\n         college_percent = some_college*100,\n         unemployment_percent = unemployment*100,\n         driving_alone_percent = driving_alone_to_work*100,\n         percent_65plus = percent_65_and_older*100,\n         latino_percent = percent_hispanic*100,\n         rural_percent = percent_rural*100) |> \n  filter(fips_code != '0') \n```\n:::\n\n\nI also made some slight changes to my data. The first was to get rid of the estimates for each state and only focus on estimates from the county. I also wanted to treat year as a continuous variable in my models but wanted to keep the `year` variable as a factor too. Then after filtering to only examine California counties I used the `str_replace_all` function from the `stringr` package to get rid of the county name after each observation. This was to make it easier to join with map data from the `maps` package. Lastly, I made the counties title case to also make joining the observations easier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty <- county |> \n  filter(str_detect(fips_code, '000$', negate = TRUE))\n\ncounty$year_num <- as.numeric(county$year)\n\nca <- county |> \n  filter(state == 'CA') |> \n  mutate(no_name_county = str_replace_all(county_name, '_county', ''))\n\nca$no_name_county <- str_to_title(ca$no_name_county)\n```\n:::\n\n\n### Models\n\nNow when running the first model, I was first interested in examining if there was an increase in LTPA engagement in all California counties from 2016 to 2020. From the finding below, it shows that in California, there was a decrease in LTPA over that time. It's also important to note that `lmerTest` and `lme4` both have a `lmer` function. By namespacing them with two colons, you can see that the summary information is slightly different.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreliminary_ltpa_long <- lmerTest::lmer(ltpa_percent ~ year_num + (1 | county_fips_code), data = ca,\n                              REML = FALSE)\nsummary(preliminary_ltpa_long)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by maximum likelihood . t-tests use Satterthwaite's\n  method [lmerModLmerTest]\nFormula: ltpa_percent ~ year_num + (1 | county_fips_code)\n   Data: ca\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1427.9    1442.5    -709.9    1419.9       286 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-5.6854 -0.3709  0.0361  0.5377  1.7084 \n\nRandom effects:\n Groups           Name        Variance Std.Dev.\n county_fips_code (Intercept) 7.187    2.681   \n Residual                     5.174    2.275   \nNumber of obs: 290, groups:  county_fips_code, 58\n\nFixed effects:\n              Estimate Std. Error         df t value            Pr(>|t|)    \n(Intercept) 1923.40172  190.60225  231.84941  10.091 <0.0000000000000002 ***\nyear_num      -0.91276    0.09445  231.84760  -9.664 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n         (Intr)\nyear_num -1.000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprelim_ltpa_lmer <- lme4::lmer(ltpa_percent ~ year_num +(1 | county_fips_code), data = ca,\n                              REML = FALSE)\nsummary(prelim_ltpa_lmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by maximum likelihood  ['lmerMod']\nFormula: ltpa_percent ~ year_num + (1 | county_fips_code)\n   Data: ca\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1427.9    1442.5    -709.9    1419.9       286 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-5.6854 -0.3709  0.0361  0.5377  1.7084 \n\nRandom effects:\n Groups           Name        Variance Std.Dev.\n county_fips_code (Intercept) 7.187    2.681   \n Residual                     5.174    2.275   \nNumber of obs: 290, groups:  county_fips_code, 58\n\nFixed effects:\n              Estimate Std. Error t value\n(Intercept) 1923.40172  190.60225  10.091\nyear_num      -0.91276    0.09445  -9.664\n\nCorrelation of Fixed Effects:\n         (Intr)\nyear_num -1.000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nltpa_null_icc <- as_tibble(VarCorr(preliminary_ltpa_long))\n\nltpa_null_icc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  grp              var1        var2   vcov sdcor\n  <chr>            <chr>       <chr> <dbl> <dbl>\n1 county_fips_code (Intercept) <NA>   7.19  2.68\n2 Residual         <NA>        <NA>   5.17  2.27\n```\n\n\n:::\n\n```{.r .cell-code}\ncounty_icc_2level(ltpa_null_icc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5814093\n```\n\n\n:::\n:::\n\n\nAlong with the fixed effects, we also got our random effects for both differences found between counties for LTPA engagement and differences within counties for LTPA engagement. This shows that there was a good amount of variation between counties (σ2 = 7.19) but also a large amount of variation within each county in California (σ2 = 5.17). Using the function to calculate the ICC, it found that county differences attributed to 58% of the variation in LTPA engagement. Something that should be considered is the potential for heteroscedastic residual variance at level 1. There is also the issue that the residuals could suggest spatial autocorrelation or clustering within these counties. Maybe I'll create something on these soon. But for the time being, lets move on to what was found for the twitter conference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nltpa_long_access <- lmer(ltpa_percent ~ year_num + violent_crime + obesity_percent + median_household_income + rural_percent +\n                           access_pa_percent + (1 | county_fips_code), data = ca,\n                         REML = FALSE)\n\nanova(preliminary_ltpa_long, ltpa_long_access)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: ca\nModels:\npreliminary_ltpa_long: ltpa_percent ~ year_num + (1 | county_fips_code)\nltpa_long_access: ltpa_percent ~ year_num + violent_crime + obesity_percent + median_household_income + rural_percent + access_pa_percent + (1 | county_fips_code)\n                      npar    AIC    BIC  logLik -2*log(L)  Chisq Df\npreliminary_ltpa_long    4 1427.9 1442.5 -709.93    1419.9          \nltpa_long_access         9 1237.4 1270.4 -609.69    1219.4 200.47  5\n                                 Pr(>Chisq)    \npreliminary_ltpa_long                          \nltpa_long_access      < 0.00000000000000022 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nother_var <- lmer(ltpa_percent ~ year_num + violent_crime + obesity_percent + median_household_income + rural_percent + (1 | county_fips_code), data = ca,\n                         REML = FALSE)\n\nanova(other_var, ltpa_long_access)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: ca\nModels:\nother_var: ltpa_percent ~ year_num + violent_crime + obesity_percent + median_household_income + rural_percent + (1 | county_fips_code)\nltpa_long_access: ltpa_percent ~ year_num + violent_crime + obesity_percent + median_household_income + rural_percent + access_pa_percent + (1 | county_fips_code)\n                 npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)  \nother_var           8 1240.1 1269.4 -612.04    1224.1                       \nltpa_long_access    9 1237.4 1270.4 -609.69    1219.4 4.6883  1    0.03037 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWith the inclusion of several predictors for fixed effects, a likelihood ratio test was conducted to see if the inclusion of these fixed effects revealed a significantly better fitting model. The inclusion of these predictors revealed a better fitting model. It would probably be better to see if the inclusion of one variable of interest, such as access, resulted in a better fitting model than a model with the other social determinants of health. As can be see here, the likelihood ratio test of including only access still resulted in a signifcantly better fitting model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ltpa_long_access)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by maximum likelihood . t-tests use Satterthwaite's\n  method [lmerModLmerTest]\nFormula: \nltpa_percent ~ year_num + violent_crime + obesity_percent + median_household_income +  \n    rural_percent + access_pa_percent + (1 | county_fips_code)\n   Data: ca\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1237.4    1270.4    -609.7    1219.4       281 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-4.8388 -0.5546  0.0010  0.6179  2.4921 \n\nRandom effects:\n Groups           Name        Variance Std.Dev.\n county_fips_code (Intercept) 1.286    1.134   \n Residual                     3.139    1.772   \nNumber of obs: 290, groups:  county_fips_code, 58\n\nFixed effects:\n                              Estimate     Std. Error             df t value\n(Intercept)             1138.319794589  193.185926848  289.539333104   5.892\nyear_num                  -0.517087682    0.096244053  289.372087931  -5.373\nviolent_crime             -0.001434185    0.001190066   82.732968339  -1.205\nobesity_percent           -0.602338792    0.043760246  262.848571777 -13.765\nmedian_household_income    0.000004822    0.000014701  102.262967759   0.328\nrural_percent             -0.012178273    0.007671490   63.273090793  -1.587\naccess_pa_percent          0.027194696    0.012124625  153.692793487   2.243\n                                    Pr(>|t|)    \n(Intercept)                     0.0000000106 ***\nyear_num                        0.0000001597 ***\nviolent_crime                         0.2316    \nobesity_percent         < 0.0000000000000002 ***\nmedian_household_income               0.7436    \nrural_percent                         0.1174    \naccess_pa_percent                     0.0263 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) yer_nm vlnt_c obsty_ mdn_h_ rrl_pr\nyear_num    -1.000                                   \nviolent_crm  0.116 -0.118                            \nobsty_prcnt  0.489 -0.494 -0.100                     \nmdn_hshld_n  0.586 -0.589  0.203  0.452              \nrural_prcnt  0.260 -0.264  0.135  0.203  0.447       \naccss_p_prc -0.147  0.142 -0.018  0.054 -0.341  0.158\nfit warnings:\nSome predictor variables are on very different scales: consider rescaling\n```\n\n\n:::\n:::\n\n\nThe model summary suggests that the fixed effect of access on LTPA engagement was significantly associated. The thing that stands out the most here is that the inclusion of the predictors resulted in more variation within counties than between counties. So lets look into that more closely.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nltpa_access_icc <- as_tibble(VarCorr(ltpa_long_access))\nltpa_access_icc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  grp              var1        var2   vcov sdcor\n  <chr>            <chr>       <chr> <dbl> <dbl>\n1 county_fips_code (Intercept) <NA>   1.29  1.13\n2 Residual         <NA>        <NA>   3.14  1.77\n```\n\n\n:::\n\n```{.r .cell-code}\ncounty_icc_2level(ltpa_access_icc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2906253\n```\n\n\n:::\n:::\n\n\nThe ICC suggests that 29% of the variation explained is from differences between counties. It is also beneficial to look at all of this through visuals.\n\n### Visuals Prep\n\nBelow we'll start by using the `maps` package to get county-level data of the contiguous United States. The steps below were to make sure this data frame joined with the county health rankings data we had created previously.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nus <- map_data(map = 'county')\n\nus <- us |> \n  janitor::clean_names() |> \n  mutate(state = region,\n         no_name_county = subregion) \n\nus$state <- str_replace_all(us$state, pattern = \" \", replacement = \"_\")\nus$no_name_county <- str_replace_all(us$no_name_county, pattern = \" \", replacement = \"_\")\n\nus <- us |> \n  mutate(state = recode(state, 'alabama' = 'AL','alaska' = 'AK','arizona' = 'AZ','arkansas' = 'AR',\n                        'california' = 'CA','colorado' = 'CO','connecticut' = 'CT',\n                        'delaware' = 'DE',\n                        'florida' = 'FL',\n                        'georgia' = 'GA',\n                        'hawaii' = 'HI',\n                        'idaho' = 'ID','illinois' = 'IL','indiana' = 'IN','iowa' = 'IA',\n                        'kansas' = 'KS','kentucky' = 'KY',\n                        'louisiana' = 'LA',\n                        'maine' = 'ME','maryland' = 'MD','massachusetts' = 'MA','michigan' = 'MI','minnesota' = 'MN','mississippi' = 'MS','missouri' = 'MO','montana' = 'MT',\n                        'nebraska' = 'NE','nevada' = 'NV','new hampshire' = 'NH','new jersey' = 'NJ','new mexico' = 'NM','new york' = 'NY','north carolina' = 'NC','north dakota' = 'ND',\n                        'ohio' = 'OH','oklahoma' = 'OK','oregon' = 'OR',\n                        'pennsylvania' = 'PA',\n                        'rhode island' = 'RI',\n                        'south carolina' = 'SC','south dakota' = 'SD',\n                        'tennessee' = 'TN','texas' = 'TX',\n                        'utah' = 'UT',\n                        'vermont' = 'VT','virginia' = 'VA',\n                        'washington' = 'WA','west virginia' = 'WV','wisconsin' = 'WI','wyoming' = 'WY'))\n\ncounty <- county |>\n  mutate(no_name_county = str_replace_all(county_name, '_county', ''))\n\nvisual <- right_join(us, county, by = c('state', 'no_name_county'))\n\nca_visual <- visual |> \n  filter(state == 'CA') |>\n  filter(no_name_county != 'california')\n```\n:::\n\n\n### Visualizing model\n\nOne way to visualize the variation between counties in our final model (`ltpa_long_access`) is to use a caterpillar plot. This allows you to view variation in the residuals of each county for your outcome. From the visual, you can see the differences between Humboldt County and Tehama County.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmain_effects_var <- ranef(ltpa_long_access, condVar = TRUE)\n\nmain_effects_var <- as.data.frame(main_effects_var)\n\nmain_effects_var <- main_effects_var |> \n  mutate(main_effects_term = term,\n         county_fips_code = grp,\n         main_effects_diff = condval,\n         main_effects_se = condsd,\n         county_fips_code = as.numeric(county_fips_code))\n\nmain_effects_var$no_name_county <- unique(ca$no_name_county)\n\nmain_effects_var |> \n  ggplot(aes(fct_reorder(no_name_county, main_effects_diff), main_effects_diff)) +\n  geom_errorbar(aes(ymin = main_effects_diff + qnorm(0.025)*main_effects_se,\n                  ymax = main_effects_diff + qnorm(0.975)*main_effects_se)) +\n  geom_point(aes(color = no_name_county)) +\n  coord_flip() +\n  labs(x = ' ',\n     y = 'Differences in Leisure-time Physical Activity',\n     title = 'Variation in Leisure-time Physical Activity\\nAcross California Counties') +\n  theme(legend.position = 'none')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThis plot shows the fixed effect of access and LTPA across the various years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nca |> \n  mutate(year = as.factor(year)) |> \n  ggplot(aes(access_pa_percent, ltpa_percent)) +\n  geom_point(aes(color = year)) +\n  geom_smooth(color = 'dodgerblue',\n            method = 'lm', se = FALSE, size = 1) +\n  theme(legend.title = element_blank()) +\n  labs(x = 'Access to Physical Activity Opportunities',\n       y = 'Leisure-time Physical Activity',\n       title = 'The Statewide Association of Access\\nand Physical Activity')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nFinally, a gif of the change of LTPA from 2016 to 2020.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gganimate)\n\nca_animate <- ca_visual |>\n  ggplot(aes(frame = year,\n             cumulative = TRUE)) +\n  geom_polygon(aes(x = long, y = lat, \n                   group = group, \n                   fill = ltpa_percent),\n               color = 'black') +\n  scale_fill_gradientn(colors = brewer.pal(n = 5, name = 'RdYlGn')) + \n  theme_classic() +\n  transition_time(year) +\n  labs(x = 'Longitude',\n       y = 'Latitude',\n       title = 'Leisure-time Physical Activity\\nChange Over Time',\n       subtitle = 'Year: {frame_time}') +\n  theme(legend.title = element_blank(),\n        legend.text = element_text(size = 12),\n        axis.text.x = element_text(size = 10),\n        axis.text.y = element_text(size = 10),\n        plot.title = element_text(size = 20),\n        plot.subtitle = element_text(size = 18))\n\nlibrary(gifski)\nanimate(ca_animate, renderer = gifski_renderer())\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.gif)\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}