---
title: "Shiny App for Assessing Proficiency" 
subtitle: |
  "Using Diagnostic Classification Models"
# image: 
categories: [cmdstanpy, python, bayesian, stan, pandas, dcm, shiny]
date: 2026-05-01
# citation:
  # url:
draft: true
execute:
    message: false
    warning: false
params:
  slug: dcm-app
  date: 2026-05-01
---

For this post I wanted to discuss the tool I am creating that could hopefully help educators with an introduction to diagnostic classification models (DCM), as well as potentially use this shiny app to assess student proficiency in the skills being assessed through assignments, quizzes, or exams. Finally, my hope is that this would be particularly useful for educators with smaller classrooms. With small being subjective, I am interested in this tool being used for classrooms ranging from roughly 30 students to maybe 200 students.

While thinking about what to focus on for this post, I think this first one will go over the shiny app layout and where I would like to expand on this project.

## Background

My motivation for building this DCM shiny app was because I was working with statistics faculty at UC Berkeley as part of my postdoctoral fellowship position in data science education. I

This shiny app will be the main tool for my individual project where I hope this shiny app can be used by faculty to assess students with periodic quizzes.

## Next Steps

From thinking about what I've accomplished with this shiny app, I am now focused on creating methods for cleaning data for various types of data. Currently, I will need to focus on how to organize, document, and clean data through Prairie Learn to get DCM results to students quickly. Additionally, I'm trying to think of options for practitioners that may be able to upload photos to code incorrect values to be put in a tabular format.